openapi: 3.0.3
info:
  title: Order - OpenAPI 3.0
  description: |-
    Order API Spec
  version: 1.0.0
#servers:
#  - url: api/v1
paths:
  /order:
    post:
      tags:
        - order
      summary: Add a new order
      description: Add a new order
      operationId: addOrder
      requestBody:
        description: Create a new order
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid request
    get:
      tags:
        - order
      summary: Get all orders
      description: Get all orders
      operationId: getOrders
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          description: Invalid request
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        customerId:
          type: integer
          format: int64
          example: 10
        customerName:
          type: string
          example: John Smith
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        totalAmount:
          type: number
          format: float
          example: 25.1
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Radio
        quantity:
          type: integer
          format: int64
          example: 10
        price:
          type: number
          format: float
          example: 25.1