openapi: 3.0.3
info:
  title: Person - OpenAPI 3.0
  description: |-
    Person API Spec
  version: 1.0.0
#servers:
#  - url: api/v1
paths:
  /person:
    post:
      tags:
        - person
      summary: Add a new person
      description: Add a new person
      operationId: addPerson
      requestBody:
        description: Create a new person
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid request
    get:
      tags:
        - person
      summary: Get all persons
      description: Get all persons
      operationId: getPersons
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
        '400':
          description: Invalid request
components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: John
        age:
          type: integer
          format: int
          example: 25